apiVersion: v1
kind: Pod   
metadata:
	name: nginx-pod
	namespace: web
	labels:
    app: nginx-app
spec:
	containers:
  - name: nginx-ctr
    image: nginx
	  command: ['nginx','-g','daemon off;','-q']
      ports:
	    - containerPort: 8081	
